/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.bookmarks.customizer.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.bookmarks.customizer.model.CustomBookmarksEntry;
import com.liferay.bookmarks.customizer.model.CustomBookmarksEntryModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CustomBookmarksEntry service. Represents a row in the &quot;bec_CustomBookmarksEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CustomBookmarksEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CustomBookmarksEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomBookmarksEntryImpl
 * @see CustomBookmarksEntry
 * @see CustomBookmarksEntryModel
 * @generated
 */
@ProviderType
public class CustomBookmarksEntryModelImpl extends BaseModelImpl<CustomBookmarksEntry>
	implements CustomBookmarksEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a custom bookmarks entry model instance should use the {@link CustomBookmarksEntry} interface instead.
	 */
	public static final String TABLE_NAME = "bec_CustomBookmarksEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table bec_CustomBookmarksEntry (id_ LONG not null primary key)";
	public static final String TABLE_SQL_DROP = "drop table bec_CustomBookmarksEntry";
	public static final String ORDER_BY_JPQL = " ORDER BY customBookmarksEntry.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY bec_CustomBookmarksEntry.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.bookmarks.customizer.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.bookmarks.customizer.model.CustomBookmarksEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.bookmarks.customizer.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.bookmarks.customizer.model.CustomBookmarksEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.bookmarks.customizer.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.bookmarks.customizer.model.CustomBookmarksEntry"));

	public CustomBookmarksEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CustomBookmarksEntry.class;
	}

	@Override
	public String getModelClassName() {
		return CustomBookmarksEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CustomBookmarksEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CustomBookmarksEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CustomBookmarksEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CustomBookmarksEntryImpl customBookmarksEntryImpl = new CustomBookmarksEntryImpl();

		customBookmarksEntryImpl.setId(getId());

		customBookmarksEntryImpl.resetOriginalValues();

		return customBookmarksEntryImpl;
	}

	@Override
	public int compareTo(CustomBookmarksEntry customBookmarksEntry) {
		long primaryKey = customBookmarksEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CustomBookmarksEntry)) {
			return false;
		}

		CustomBookmarksEntry customBookmarksEntry = (CustomBookmarksEntry)obj;

		long primaryKey = customBookmarksEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CustomBookmarksEntry> toCacheModel() {
		CustomBookmarksEntryCacheModel customBookmarksEntryCacheModel = new CustomBookmarksEntryCacheModel();

		customBookmarksEntryCacheModel.id = getId();

		return customBookmarksEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(3);

		sb.append("{id=");
		sb.append(getId());

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(7);

		sb.append("<model><model-name>");
		sb.append("com.liferay.bookmarks.customizer.model.CustomBookmarksEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CustomBookmarksEntry.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CustomBookmarksEntry.class
		};
	private long _id;
	private CustomBookmarksEntry _escapedModel;
}