/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.bookmarks.customizer.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the CustomBookmarksEntry service. Represents a row in the &quot;bec_CustomBookmarksEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.bookmarks.customizer.model.impl.CustomBookmarksEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.bookmarks.customizer.model.impl.CustomBookmarksEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomBookmarksEntry
 * @see com.liferay.bookmarks.customizer.model.impl.CustomBookmarksEntryImpl
 * @see com.liferay.bookmarks.customizer.model.impl.CustomBookmarksEntryModelImpl
 * @generated
 */
@ProviderType
public interface CustomBookmarksEntryModel extends BaseModel<CustomBookmarksEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom bookmarks entry model instance should use the {@link CustomBookmarksEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this custom bookmarks entry.
	 *
	 * @return the primary key of this custom bookmarks entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this custom bookmarks entry.
	 *
	 * @param primaryKey the primary key of this custom bookmarks entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this custom bookmarks entry.
	 *
	 * @return the ID of this custom bookmarks entry
	 */
	public long getId();

	/**
	 * Sets the ID of this custom bookmarks entry.
	 *
	 * @param id the ID of this custom bookmarks entry
	 */
	public void setId(long id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CustomBookmarksEntry customBookmarksEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CustomBookmarksEntry> toCacheModel();

	@Override
	public CustomBookmarksEntry toEscapedModel();

	@Override
	public CustomBookmarksEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}